apiVersion: apps/v1
kind: Deployment
metadata:
  name: cricket-game-deployment
  namespace: cricket-game
  labels:
    app: cricket-game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cricket-game
  template:
    metadata:
      labels:
        app: cricket-game
    spec:
      containers:
      - name: cricket-game
        image: YOUR_ECR_REPO/cricket-game:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DATA_DIRECTORY
          value: "/app/data"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: cricket-game-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cricket-game-pvc
  namespace: cricket-game
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
